global_costmap:
  # global_frame: map
  update_frequency: 0.5
  publish_frequency: 1.5
  transform_tolerance: 0.5
  width: 15
  height: 15
  origin_x: -7.5
  origin_y: -7.5
  #use static map or not, if load map change to true
  static_map: true
  rolling_window: true
  inflation_radius: 2.5
  resolution: 0.05
  plugins:
  - {name: obstacles_layer ,type: "costmap_2d::ObstacleLayer"}
  - {name: inflater_layer ,type: "costmap_2d::InflationLayer"}
  - {name: static_layer,        type: "costmap_2d::StaticLayer"}

  
  
