local_costmap:
  # global_frame: odom
  update_frequency: 2.5
  publish_frequency: 2.5
  transform_tolerance: 0.25
  #do not use the static map could make navigation better
  static_map: false
  rolling_window: true
  width: 3
  height: 3
  origin_x: -1.5
  origin_y: -1.5
  resolution: 0.05 # should the same as static map resolution
  
plugins:
  - {name: obstacles ,type: "costmap_2d::VoxelLayer"}
  - {name: inflater_layer ,type: "costmap_2d::InflationLayer"}
  - {name: static_layer,        type: "costmap_2d::StaticLayer"}
